MGMT-4762 Support HEAD for ISO download
openshift/assisted-service pull request #1389
Opened 2021-03-25 12:38 UTC by mmartinv

2021-03-25 12:40 UTC, rollandf commented
/ok-to-test

2021-03-25 12:53 UTC, avishayt requested changes

2021-03-25 12:53 UTC, avishayt commented on swagger.yaml
> +        - userAuth: [admin, read-only-admin, user]
Under this line add also:
- urlAuth: []

2021-03-25 12:53 UTC, avishayt commented on swagger.yaml
> +        - application/octet-stream
```suggestion
```

2021-03-25 12:53 UTC, avishayt commented on swagger.yaml
> +          description: Success.
```suggestion
          description: Success.
          headers:
            Content-Length:
              type: integer
              description: Size of the ISO in bytes
```

2021-03-25 12:53 UTC, avishayt commented on internal/bminventory/inventory.go
> +			"Failed to download image: the image was not found (perhaps it expired) - please generate the image and try again", time.Now())
No need for this event

2021-03-25 12:53 UTC, avishayt commented on internal/bminventory/inventory.go
> +				"(perhaps it expired) - please generate the image and try again")))
```suggestion
			WithPayload(common.GenerateError(http.StatusNotFound, errors.New("The image was not found")))
```

2021-03-25 12:53 UTC, avishayt commented on internal/bminventory/inventory.go
> +		fmt.Sprintf(`Started image download (image type is "%s")`, cluster.ImageInfo.Type), time.Now())
```suggestion
	imgSize, err := b.objectHandler.GetObjectSizeBytes(ctx, imgName)
	if err != nil {
		log.WithError(err).Errorf("Failed to get ISO size for cluster %s", cluster.ID.String())
		return common.NewApiError(http.StatusBadRequest, err)
	}
```

2021-03-25 12:53 UTC, avishayt commented on internal/bminventory/inventory.go
> +		contentLength)
Fix this to return 200 and Content-Length (use the method WithContentLength)

2021-03-25 12:53 UTC, avishayt commented on internal/bminventory/inventory.go
> +func (b *bareMetalInventory) DownloadClusterISOHeaders(ctx context.Context, params installer.DownloadClusterISOHeadersParams) middleware.Responder {
Unit tests?

2021-03-29 20:25 UTC, carbonin commented
/approve

Looks good. I think you have a linting error though.
Make sure you're generating the files using the generator make targets. I think you'll want `skipper make generate-from-swagger` or maybe just go with `skipper make generate-all`

2021-03-30 05:08 UTC, avishayt commented
Can you please show the output of the API (specifically the content length) when using a full ISO and a minimal ISO?  Let's make sure it's as expected.  Thanks!

2021-03-30 05:20 UTC, rwsu reviewed
I would suggest adding to the commit message with something like: "Adds content-length header for ISO downloads. Content-length header and status 200 are required by Ironic."

2021-04-01 15:43 UTC, flaper87 commented
@mmartinv hope you don't mind but I took over this PR and pushed the fixes for CI here https://github.com/openshift/assisted-service/pull/1430

I also addressed the comments from @avishayt and @rwsu 

I think we can close this one :)

2021-04-01 15:43 UTC, flaper87 commented
/close

2021-04-01 15:43 UTC, closed without merging