MGMT-5281: Handle conflicts in CRDs status updates
openshift/assisted-service pull request #1624
Opened 2021-05-01 13:37 UTC by RazRegev

In the time between getting the resource to reconcile
and updating its status, the object can become out of
date (if edited by user for example).
When it happens we will attempt to reconcile this crd
again immediately with the up-to-date data.

```
time="2021-04-20T08:04:50Z" level=error msg="failed to update agent Status" func="github.com/openshift/assisted-service/internal/controller/controllers.(*AgentReconciler).updateStatus" file="/go/src/github.com/openshift/origin/internal/controller/controllers/agent_controller.go:132" error="Operation cannot be fulfilled on agents.agent-install.openshift.io \"a72237e3-f7f5-46d4-965e-ea644056917a\": the object has been modified; please apply your changes to the latest version and try again"

time="2021-04-20T08:05:01Z" level=error msg="failed to update ClusterDeployment Status" func="github.com/openshift/assisted-service/internal/controller/controllers.(*ClusterDeploymentsReconciler).updateStatus" file="/go/src/github.com/openshift/origin/internal/controller/controllers/clusterdeployments_controller.go:599" error="Operation cannot be fulfilled on clusterdeployments.hive.openshift.io \"test-cluster\": the object has been modified; please apply your changes to the latest version and try again"

```

2021-05-01 21:54 UTC, RazRegev commented
/hold

2021-05-01 21:56 UTC, RazRegev commented
/cc @rollandf

2021-05-01 21:56 UTC, RazRegev commented
/cc @djzager

2021-05-02 08:11 UTC, RazRegev commented
/cc @nmagnezi

2021-05-02 11:47 UTC, rollandf commented
I think it looks OK, lets' wait a few for others to review

2021-05-02 17:30 UTC, mhrivnak requested changes

2021-05-02 17:30 UTC, mhrivnak commented on internal/controller/controllers/crd_utils.go
> +	ctx context.Context,
nit: `ctx` by convention should be the first argument. From [the docs](https://golang.org/pkg/context/):

"Do not store Contexts inside a struct type; instead, pass a Context explicitly to each function that needs it. The Context should be the first parameter, typically named ctx:"

2021-05-04 14:51 UTC, nmagnezi commented on internal/controller/controllers/crd_utils.go
> +			obj.GetObjectKind().GroupVersionKind().Kind, obj.GetName())
it also log the namespace

2021-05-04 14:51 UTC, nmagnezi commented on internal/controller/controllers/crd_utils.go
> +	log.WithError(err).Errorf("Failed to update %s Status of %s",
ditto

2021-05-04 14:51 UTC, nmagnezi commented on internal/controller/controllers/agentserviceconfig_controller_test.go
> +		Log:       logrus.New(),
can you explain why?

2021-05-06 01:14 UTC, djzager requested changes
I'm not wholly convinced that the juice is worth the squeeze on this one. If we collectively think that this is the way to go, I would rather us:

1. Provide the function to check if the error `IsOptimisticLockError`
2. Establish the pattern for what to do when we want to handle that error.

2021-05-31 12:09 UTC, closed without merging