OCPBUGSM-30350: Add Progress info to Agent Status
openshift/assisted-service pull request #2004
Opened 2021-06-15 08:13 UTC by rollandf

# Description
Add Progress field in Agent Status that includes:
 - CurrentStage
 - ProgressInfo
 - StageStartTime
 - StageUpdateTime

Signed-off-by: Fred Rolland <frolland@redhat.com>

# What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [x] Operator Managed Deployments
- [ ] None

# How was this code tested?

Please, select one or more if needed:

- [x] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

It's recommended to take a few extra minutes to provide more information about
how this code was tested. Here are some questions that may be worth answering:

- Should this PR be tested by the reviewer?
- Is this PR relying on CI for an e2e test run?
- Should this PR be tested in a specific environment?
- Any logs, screenshots, etc that can help with the review process?

Test-infra Agent CR Status snippet:
```
  progress:
    currentStage: Rebooting
    stageStartTime: "2021-06-15T06:45:32.877Z"
    stageUpdateTime: "2021-06-15T06:45:32.877Z"
```

# Assignees

Please, add one or two reviewers that could help review this PR.

/assign @filanov 
/assign @nmagnezi 
/assign @danielerez 

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] Reviewers have been listed
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [x] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- [ ] Are the title and description (in both PR and commit) meaningful and clear?
- [ ] Is there a bug required (and linked) for this change?
- [ ] Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

2021-06-15 11:36 UTC, nmagnezi approved these changes
/lgtm

2021-06-16 05:07 UTC, rollandf commented
/retest

2021-06-16 06:22 UTC, flaper87 commented
@rollandf will this be backported? Technically, this changes the CRD API.

It might be better to get this in now in 4.8 rather than keeping it just for 4.9 and then introducing a breaking change. What do you think?

2021-06-16 06:22 UTC, flaper87 commented
/lgtm

2021-06-16 06:23 UTC, nmagnezi requested changes
/lgtm

2021-06-16 06:23 UTC, nmagnezi commented on internal/controller/api/v1beta1/agent_types.go
> +	StageStartTime metav1.Time `json:"stageStartTime,omitempty"`
should this be `*metav1.Time` ?

2021-06-16 06:23 UTC, nmagnezi commented on internal/controller/api/v1beta1/agent_types.go
> +	StageUpdateTime metav1.Time `json:"stageUpdateTime,omitempty"`
ditto

2021-06-16 06:48 UTC, rollandf commented
> @rollandf will this be backported? Technically, this changes the CRD API.
> 
> It might be better to get this in now in 4.8 rather than keeping it just for 4.9 and then introducing a breaking change. What do you think?

Yes, it will be backported

2021-06-16 06:55 UTC, nmagnezi approved these changes
/lgtm

2021-06-16 06:56 UTC, rollandf commented on internal/controller/api/v1beta1/agent_types.go
> +	StageStartTime metav1.Time `json:"stageStartTime,omitempty"`
Done

2021-06-16 06:56 UTC, rollandf commented on internal/controller/api/v1beta1/agent_types.go
> +	StageUpdateTime metav1.Time `json:"stageUpdateTime,omitempty"`
Done

2021-06-16 07:14 UTC, rollandf commented
/test e2e-metal-assisted-operator-ztp

2021-06-16 09:10 UTC, rollandf commented
/test e2e-metal-assisted-kube-api

2021-06-16 18:06 UTC, rollandf commented
/cherry-pick ocm-2.3

2021-06-17 05:27 UTC, rollandf commented
/retest

2021-06-17 08:20 UTC, rollandf commented
/retest

2021-06-18 03:20 UTC, merged

2021-06-20 14:07 UTC, rollandf commented
/cherry-pick ocm-2.3