MGMT-6735: Add configurations for multi node spoke in ZTP
openshift/assisted-service pull request #2290
Opened 2021-07-28 00:40 UTC by lranjbar

# Assisted Pull Request

## Description

For MGMT-6735 we are adding a multi node spoke cluster in the ZTP flow. This is configuration changes made in my local dev-scripts environment to support spoke clusters.

## List all the issues related to this PR

- [ ] New Feature
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [x] CI/CD 

## What environments does this code impact?

- [x] Automation (CI, tools, etc)
- [ ] Cloud
- [x] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [x] dev-scripts environment
- [x] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Assignees

/cc @YuviGold 
/cc @osherdp
/cc @djzager 

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] Reviewers have been listed
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- [ ] Are the title and description (in both PR and commit) meaningful and clear?
- [ ] Is there a bug required (and linked) for this change?
- [ ] Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

2021-07-28 00:41 UTC, lranjbar commented
/test e2e-metal-assisted-operator-ztp

2021-07-28 06:49 UTC, osherdp requested changes

2021-07-28 06:49 UTC, osherdp commented on deploy/operator/ztp/deploy_spoke_cluster.sh
> +    fi
```suggestion
    export SPOKE_API_VIP=$(nth_ip $EXTERNAL_SUBNET 85)
    export SPOKE_INGRESS_VIP=$(nth_ip $EXTERNAL_SUBNET 87)
```

2021-07-28 06:49 UTC, osherdp commented on deploy/operator/utils.sh
> +}
nit: ending with newline

2021-07-28 06:56 UTC, YuviGold commented
Looks good to me
/test e2e-metal-assisted-operator-disconnected

2021-07-28 19:17 UTC, osherdp commented
/lgtm

2021-07-28 19:45 UTC, djzager approved these changes

2021-07-28 19:45 UTC, djzager commented on deploy/operator/ztp/assisted-installer-crds-playbook.yaml
> +    - spoke_ingress_vip: "{{ lookup('env', 'SPOKE_INGRESS_VIP') }}"
We could move these to command line arguments instead of environment...outside the scope of this PR but it's something to consider.

2021-07-29 14:02 UTC, merged

2021-07-29 14:11 UTC, osherdp commented
@lranjbar next thing is adding jobs running this flow?