MGMT-5443 Set host status to pending-user-input in case of reboot tim…
openshift/assisted-service pull request #2343
Opened 2021-08-05 14:02 UTC by eranco74

…eout

# Assisted Pull Request

## Description

Set host status to pending-user-input in case of reboot timeout.

Reboot timeout shouldn't be different from wrong boot order. 
Once the node boot properly the installation will resume

It's recommended to take a few extra minutes to provide more information about
how this code was tested. Here are some questions that may be worth answering:

- Should this PR be tested by the reviewer? no
- Is this PR relying on CI for an e2e test run? yes
- Should this PR be tested in a specific environment? no
- Any logs, screenshots, etc that can help with the review process? no

## List all the issues related to this PR

- [x] New Feature
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [x] Cloud
- [x] Operator Managed Deployments
- [x] None

## How was this code tested?

- [x] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Assignees

/cc @tsorya 
/cc @osherdp 

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] Reviewers have been listed
- [?] This change does not require a documentation update (docstring, `docs`, README, etc)
- [x] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- [ ] Are the title and description (in both PR and commit) meaningful and clear?
- [ ] Is there a bug required (and linked) for this change?
- [ ] Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

2021-08-05 14:27 UTC, osherdp commented
@eranco74 it wants the commit message to be "MGMT-5443: Set host status..." instead

2021-08-05 14:39 UTC, osherdp requested changes

2021-08-05 14:39 UTC, osherdp commented on internal/host/common.go
>  	statusInfoBinding                                          = "Host is waiting tobe bound to the cluster"
any chance you're fixing it to "to be"?
sorry about that not being related to your PR

2021-08-08 11:35 UTC, osherdp approved these changes

2021-08-08 13:41 UTC, merged

2021-08-09 16:04 UTC, eranco74 commented
This is how it looks in the assisted-service logs:
```
time="2021-08-09T15:50:06Z" level=info msg="host dd74baa8-a9b5-46af-8005-9e901bb9f1f3 from infra env c4641558-cd30-4643-855f-41723f438e5a has been updated with the following updates [status installing-pending-user-action status_info Host failed to reboot within timeout, the installation will resume once the host reboot status_updated_at 2021-08-09T15:50:06.683Z trigger_monitor_timestamp 2021-08-09 15:50:06.683116455 +0000 UTC m=+3964.140455012]"

```