NO_ISSUE - expose the assisted debug port and remove the liveness por…
openshift/assisted-service pull request #2415
Opened 2021-08-18 14:41 UTC by michaellevy101

…t as part of the patch-service make target

# Assisted Pull Request

## Description

## List all the issues related to this PR

- [ ] New Feature
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Assignees

/cc @
/cc @

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] Reviewers have been listed
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- [ ] Are the title and description (in both PR and commit) meaningful and clear?
- [ ] Is there a bug required (and linked) for this change?
- [ ] Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

2021-08-18 14:42 UTC, michaellevy101 commented
@YuviGold

2021-08-18 20:39 UTC, YuviGold approved these changes

2021-08-19 06:01 UTC, YuviGold commented
/hold

2021-08-19 07:55 UTC, YuviGold approved these changes

2021-08-19 08:39 UTC, michaellevy101 commented
/retest

2021-08-19 10:14 UTC, YuviGold commented
/unhold

2021-08-19 10:24 UTC, flaper87 requested changes
/hold

Could you please expand the template description and fix the PR title?

2021-08-22 18:02 UTC, YuviGold commented
/retest

2021-08-24 07:08 UTC, michaellevy101 commented
@flaper87 done

2021-08-24 07:09 UTC, michaellevy101 commented
/retest

2021-08-24 12:47 UTC, YuviGold approved these changes

2021-08-24 14:53 UTC, YuviGold commented
/unhold

2021-08-24 18:55 UTC, merged