Subsystem test bmac flow
openshift/assisted-service pull request #2882
Opened 2021-11-05 11:37 UTC by alknopfler

# Assisted Pull Request

## Description

This is the subsystem test for the bmac flow in order to add a new bmh host to day2 cluster 
MGMT-5235 

## List all the issues related to this PR

- [ ] New Feature
- [ ] Bug fix
- [x ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [x ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Assignees

/cc @flaper87 
/assign @flaper87 

## Checklist

- [x ] Title and description added to both, commit and PR.
- [x ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x ] Reviewers have been listed
- [ x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- [ ] Are the title and description (in both PR and commit) meaningful and clear?
- [ ] Is there a bug required (and linked) for this change?
- [ ] Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

2021-11-05 12:29 UTC, alknopfler commented
/retest

2021-11-11 12:52 UTC, flaper87 commented
/retest

2021-11-12 20:41 UTC, alknopfler commented
/retest

2021-11-21 07:06 UTC, rollandf commented
/test subsystem-aws

2021-11-24 09:26 UTC, flaper87 commented
/test subsystem-aws

2021-11-24 09:27 UTC, flaper87 requested changes

2021-11-29 07:36 UTC, rollandf commented on subsystem/kubeapi_test.go
> +			time.Sleep(time.Second * 10)
Do not use Sleep, it will result in flaky test.
If you need to wait to something that should be created/updated, use `Eventually`

2022-01-12 09:12 UTC, alknopfler commented
/approve cancel

2022-01-12 09:13 UTC, alknopfler commented
/reopen

2023-05-07 00:01 UTC, closed without merging