Allow /30 machine cidr in SNO
openshift/assisted-service pull request #3087
Opened 2021-12-21 10:42 UTC by tsorya

# Assisted Pull Request

## Description
 We should allow to set mahcine cidr with /30 value in case of sno

## List all the issues related to this PR

- [ ] New Feature
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Assignees

/cc @
/cc @

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] Reviewers have been listed
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- [ ] Are the title and description (in both PR and commit) meaningful and clear?
- [ ] Is there a bug required (and linked) for this change?
- [ ] Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

2021-12-21 21:36 UTC, tsorya commented
/retest

2021-12-21 22:49 UTC, romfreiman commented on internal/network/cidr_validations.go
> +func VerifyMachineCIDR(cidrStr string, sno bool) error {
isSNO

2021-12-22 06:39 UTC, flaper87 requested changes
In addition to Rom's comment (rename param to `isSNO` instead of using `sno`) I think it would be useful to expand on the PR description on why this is needed.

The current description says we *should* do this but it doesn't elaborate on why, which is important for the logs, history, and helping others learn from the work being done :)

2021-12-22 08:29 UTC, eranco74 commented on internal/bminventory/inventory.go
> +			if err = network.VerifyMachineCIDR(string(machineNetwork.Cidr), common.IsSingleNodeCluster(cluster)); err != nil {
What's this syntax?
`,` between conditions

2021-12-22 08:47 UTC, eranco74 commented
/lgtm

2021-12-22 11:28 UTC, romfreiman commented
/approve
/lgtm

2021-12-22 21:46 UTC, merged

2021-12-29 16:01 UTC, osherdp commented
/cherry-pick cloud-hotfix-releases

2021-12-29 16:03 UTC, osherdp commented
/cherry-pick cloud_hotfix_releases

2022-01-25 16:48 UTC, tsorya commented
/cherry-pick release-ocm-2.4

2022-01-25 19:59 UTC, tsorya commented
/retitle Bug 2045860: Allow /30 machine cidr in SNO

2022-01-25 20:00 UTC, tsorya commented
?

2022-01-25 20:01 UTC, tsorya commented
/bugzilla refresh

2022-01-25 20:01 UTC, tsorya commented
/cherry-pick release-ocm-2.4

2022-01-25 20:05 UTC, tsorya commented
/cherry-pick release-ocm-2.4