NO-ISSUE: Fix assisted_service_build image can't find minikube
openshift/assisted-service pull request #3188
Opened 2022-01-12 12:40 UTC by eliorerz

```
$ minikube status
E0112 13:26:37.720563 1062458 status.go:261] The "minikube" host does not exist!
minikube
type: Control Plane
host: Nonexistent
kubelet: Nonexistent
apiserver: Nonexistent
kubeconfig: Nonexistent
```

/cc @osherdp @slaviered

2022-01-12 12:49 UTC, eliorerz commented
/retest

2022-01-12 12:49 UTC, eliorerz commented
/test

2022-01-12 12:50 UTC, eliorerz commented
/test ?

2022-01-12 13:13 UTC, filanov commented on Dockerfile.assisted-service-build
> +RUN yum install -y epel-release && yum install -y gcc genisoimage jq git && yum install libvirt-client libvirt-devel -y
why do you need another command? any specific reason not to do
```suggestion
RUN yum install -y epel-release && yum install -y gcc genisoimage jq git libvirt-client libvirt-devel
```

2022-01-12 13:33 UTC, osherdp requested changes

2022-01-12 13:33 UTC, osherdp commented on Dockerfile.assisted-service-build
> +RUN yum install -y epel-release && yum install -y gcc genisoimage jq git libvirt-client libvirt-devel
```suggestion
RUN yum install -y epel-release \
    && yum install -y --setopt=skip_missing_names_on_install=False \
        gcc genisoimage jq git libvirt-client libvirt-devel
```

2022-01-12 13:35 UTC, osherdp commented on Dockerfile.assisted-service-build
> +RUN yum install -y epel-release && yum install -y gcc genisoimage jq git libvirt-client libvirt-devel
otherwise, it will not verify all those packages exist (and it will just skip everything it couldn't find)

2022-01-13 07:01 UTC, filanov commented
@eliorerz please keep the template of the PRs in assisted-service

2022-01-13 12:05 UTC, osherdp approved these changes

2022-01-14 06:35 UTC, merged