MGMT-9122: remove v1 EnableHost DisableHost
openshift/assisted-service pull request #3387
Opened 2022-02-23 08:23 UTC by slaviered

EnableHost/DisableHost are APIs that were replaced in V2
by either unbinding to deregistration.

This PR returns 404 when those APIs are called and removes
unnecessary code branches that implemented the old APIs.

Tests that verify those APIs were removed.
In other cases, EnableHost or DisableHost were used to induce
an error or check route processing.
Then, they were replaced with other calls.

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Assignees

/cc @
/cc @

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] Reviewers have been listed
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

2022-02-23 08:23 UTC, slaviered commented
/assign @nmagnezi

2022-02-23 09:40 UTC, filanov commented
do a grep on HostStatusDisabled and make sure that it doesn't exist anymore it's not relevant for v2

2022-02-23 10:07 UTC, slaviered commented
/hold

2022-02-24 12:49 UTC, slaviered commented
/retest

2022-02-24 13:00 UTC, filanov commented
LGTM, @nmagnezi i prefer that you would give another look

2022-02-24 15:17 UTC, nmagnezi requested changes

2022-02-24 15:17 UTC, nmagnezi commented on pkg/auth/authz_handler_test.go
> -func disableHost(ctx context.Context, cli *client.AssistedInstall) error {
what about `enableHost()` in line 814 at this file?

2022-02-24 15:17 UTC, nmagnezi commented on pkg/auth/authz_handler_test.go
> -		{
the test involving `enableHost()` in line 405 should probably go away as well

2022-02-24 15:17 UTC, nmagnezi commented on internal/ignition/ignition.go
>  		switch {
Given that now we have just a case and a default, does switch-case still makes sense here?

2022-02-24 15:34 UTC, nmagnezi approved these changes
/lgtm

2022-02-24 17:45 UTC, slaviered commented
/test e2e-metal-assisted-operator-ztp

2022-02-24 20:02 UTC, slaviered commented
/hold cancel

2022-02-25 00:58 UTC, merged