NO-ISSUE: Change quay ocpmetal to edge-infrastructure
openshift/assisted-service pull request #3495
Opened 2022-03-16 15:46 UTC by mkowalski

quay.io/ocpmetal repository has been deprecated for quite a while in
favour of quay.io/edge-infrastructure. This PR changes all the
references to the old one.

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Assignees

/cc @osherdp 
/cc @mresvanis 

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] Reviewers have been listed
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

2022-03-16 16:03 UTC, osherdp requested changes
be aware that prow will not take into consideration Dockerfile changes in this PR (but will take them from master)
so additional testing is needed in addition to CI

2022-03-16 16:03 UTC, osherdp commented on deploy/wiremock/wiremock-deployment.yaml
> +          image: quay.io/edge-infrastructure/wiremock
Also shouldn't exist

2022-03-16 16:03 UTC, osherdp commented on deploy/postgres/postgres-deployment-ephemeral.yaml
> +          image: quay.io/edge-infrastructure/postgresql-12-centos7
```suggestion
          image: quay.io/centos7/postgresql-12-centos7
```

2022-04-26 12:12 UTC, mkowalski commented
/close

Not relevant anymore

2022-04-26 12:13 UTC, closed without merging