[MGMT-2138] Added asisted-iso-create rhcos image download back
openshift/assisted-service pull request #358
Opened 2020-09-14 12:21 UTC by mvazquezc

Adds the RHCOS image download back to the Dockerfile for livecd iso creation.

2020-09-14 15:10 UTC, ybettan commented
/retest

2020-09-15 11:32 UTC, ybettan commented
/test

2020-09-15 11:33 UTC, ybettan commented
/retest

2020-09-15 12:58 UTC, ybettan commented
/retest

2020-09-16 00:11 UTC, rwsu requested changes

2020-09-16 00:11 UTC, rwsu commented on README.md
> +## Update Discovery Image base OS
Lines 105-118 repeats above.

2020-09-16 07:09 UTC, mvazquezc commented on README.md
> +## Update Discovery Image base OS
Fixed!

2020-10-05 10:41 UTC, avishayt approved these changes

2020-10-05 13:12 UTC, avishayt commented
/unhold

2020-10-05 14:00 UTC, mvazquezc commented
Closed in favor of: #486

2020-10-05 14:00 UTC, closed without merging