Adding new documentation format and openning the user-guide for more contributions that will come soon
openshift/assisted-service pull request #368
Opened 2020-09-15 10:41 UTC by jparrill

- Adding MkDocs (readthedocs) documentation format
- Adding structure for basic sections
- Adding user-guide (in construction)

2020-09-16 06:07 UTC, avishayt requested changes
A few comments inline.  Can we get a tech writer to review?

2020-09-16 06:07 UTC, avishayt commented on README.md
> +To add modifications and sections on the documentation, we are using [MkDocs](https://www.mkdocs.org/), to install the dependencies, just execute this:
```suggestion
We are using [MkDocs](https://www.mkdocs.org/) to build the documentation.  It can be installed by executing:
```

2020-09-16 06:07 UTC, avishayt commented on README.md
> +- If you add a new section, modify the `mkdocs.yaml`
```suggestion
- When adding a new section, modify the `mkdocs.yaml` file accordingly.
```

2020-09-16 06:07 UTC, avishayt commented on README.md
> +- If you modify an existant one, test it with
```suggestion
- When you modifying an existing one, test it by executing:
```

2020-09-16 06:07 UTC, avishayt commented on docs/user-guide/assisted-service-on-local.md
> +# Running OpenShift Assisted Service on Local
```suggestion
# Running OpenShift Assisted Service (OAS) on local machine
```

2020-09-16 07:53 UTC, jparrill commented
> A few comments inline. Can we get a tech writer to review?

Could be, maybe @romfreiman knows someone to review this kind of PR's

2020-10-06 09:55 UTC, avishayt approved these changes

2020-10-06 19:11 UTC, YuviGold commented
@jparrill Can you put the `site` directory under `docs` as well?

2020-10-06 19:46 UTC, jparrill commented
> @jparrill Can you put the `site` directory under `docs` as well?

I cannot:

```
λ jparrill-assisted-service git:(rfe/user_guide) [✘!] via 🐹 v1.14.9 mkdocs build
ERROR   -  Config value: 'site_dir'. Error: The 'site_dir' should not be within the 'docs_dir' as this leads to the build directory being copied into itself and duplicate nested files in the 'site_dir'.(site_dir: '/home/jparrill/RedHat/RedHat_Engineering/edge/mgmt-integration/assisted_installer/forks/jparrill-assisted-service/docs/site', docs_dir: '/home/jparrill/RedHat/RedHat_Engineering/edge/mgmt-integration/assisted_installer/forks/jparrill-assisted-service/docs') 

Aborted with 1 Configuration Errors!
```

2020-10-07 09:50 UTC, YuviGold approved these changes
LGTM

2020-10-07 12:53 UTC, YuviGold commented
/unhold

2020-10-08 06:21 UTC, jparrill commented
/retest

2020-10-08 11:54 UTC, maorfr commented
/retest

2020-10-08 12:03 UTC, jparrill commented
@avishayt could you please add a LGTM to this one, I guess the only thing it needs is another LGTM label

2020-10-08 12:13 UTC, merged