WIP: MGMT-9914: Integration of the ODF LVM operator with Assisted Ins…
openshift/assisted-service pull request #3921
Opened 2022-06-09 11:31 UTC by dvachhan

Currently, ODF capabilities are not provided with SNO from the AI. Since the ODF LVM operator went tech preview in ODF 4.10, this PR integrates the ODF LVM operator with SNO

## List all the issues related to this PR

- [x] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [x] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Assignees

/cc @rewantsoni 
/cc @

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] Reviewers have been listed
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [x] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

2022-06-21 08:35 UTC, rewantsoni requested changes

2022-07-06 13:02 UTC, dvachhan commented
/assign @flaper87 @avishayt

2022-07-17 09:37 UTC, akalenyu commented
Should we disable HPP entirely then?
AFAIU that is the decision that was made, and we want to avoid a situation where both are installed?
Knob should be available at https://github.com/openshift/assisted-service/blob/066bff08948a41b00785285b3e0879ecd8498e12/openshift/template.yaml#L114-L115

2022-07-26 07:27 UTC, gamli75 commented on internal/operators/lvm/config.go
> +	LvmMinDiskSizeGB       int64  `envconfig:"LVM_MIN_DISK_SIZE_GB" default:"0"`
Why 0?  and I don't see that we use this parameter

2022-07-26 07:27 UTC, gamli75 commented on internal/operators/lvm/config.go
> +	LvmMinOpenshiftVersion string `envconfig:"LVM_MIN_OPENSHIFT_VERSION" default:"4.12.0"`
We want to add LVMO in 4.11 as a tech preview -  why the default is 4.12?

2022-07-26 07:27 UTC, gamli75 commented on internal/operators/lvm/lvm_operator.go
> +		message := "ODF LVM operator is only supported for openshift versions 4.12.0 and above"
same remark as before - we want it as tech preview in 4.11

2022-07-26 12:41 UTC, akalenyu reviewed
Looks good!

Mainly concerned with how HPP is disabled with this PR. I might be missing it entirely
@aglitke

2022-07-26 12:41 UTC, akalenyu commented on internal/operators/lvm/manifest.go
> +kind: LVMCluster
Are we not creating a `StorageClass` as well? does it get created by some operator?
Just thinking we might be better off creating our own one and setting it as default

2022-07-26 17:37 UTC, gamli75 commented
> Looks good!
> 
> Mainly concerned with how HPP is disabled with this PR. I might be missing it entirely (current IIUC they will both get deployed on SNO installs) cc @aglitke

We have a different epic for replacing HPP, see: https://issues.redhat.com/browse/MGMT-11046 
the requirements are:
![image](https://user-images.githubusercontent.com/62331841/181073622-a18d2a0b-9c43-4b37-b6c0-945a46ecd315.png)

Do you think that there will be a problem if the user will install CNV(HPP + LSO) & LVMO in OCP 4.11?

2022-08-01 10:27 UTC, akalenyu commented
> > Looks good!
> > Mainly concerned with how HPP is disabled with this PR. I might be missing it entirely (current IIUC they will both get deployed on SNO installs) cc @aglitke
> 
> We have a different epic for replacing HPP, see: https://issues.redhat.com/browse/MGMT-11046 the requirements are: ![image](https://user-images.githubusercontent.com/62331841/181073622-a18d2a0b-9c43-4b37-b6c0-945a46ecd315.png)
> 
> Do you think that there will be a problem if the user will install CNV(HPP + LSO) & LVMO in OCP 4.11?

Yes, the first thing that comes to mind is the extra non-installation disk requirement;
HPP also requires that so I imagine we'll have them fighting over this.

Another nuance is which storage class takes the "default" place.
4.11 would have HPP as default, and 4.12 will have LVMO as the default.
I think in both cases we'll have to create the storage class for LVMO ourselves to control the default storage class annotation,
WDYT?

2022-08-02 08:45 UTC, gamli75 commented
closed this PR - was replaced by https://github.com/openshift/assisted-service/pull/4197

2022-08-02 08:45 UTC, closed without merging