NO-ISSUE: Fix master's manifest file pattern for oVirt provider
openshift/assisted-service pull request #3971
Opened 2022-06-17 09:53 UTC by mmartinv

It looks like the master's manifest file names have been changed
and makes the installer to fail when activating the oVirt provider.

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Assignees

/cc @eliorerz 
/cc @osherdp 
/cc @michaellevy101 

## Checklist

- [x] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] Reviewers have been listed
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

2022-06-19 05:50 UTC, osherdp commented
/test edge-subsystem-aws

2022-06-19 05:54 UTC, osherdp requested changes
Looks good, just add unit tests when done

2022-06-27 11:29 UTC, mmartinv commented
/retest

2022-06-27 11:38 UTC, mmartinv commented
> Looks good, just add unit tests when done

Done, please take a look as I needed to make some more changes.
Once you're done could you please take a look at  #3972 which depends on this PR?

2022-06-27 12:18 UTC, osherdp requested changes

2022-06-27 12:18 UTC, osherdp commented on internal/provider/ovirt/ignition.go
> +	}
I think it's worth propagating the error, for cases where we have a malformed pattern

2022-06-27 12:18 UTC, osherdp commented on internal/provider/ovirt/ignition.go
> +		return errors.New(fmt.Sprintf("more than one file found '%s'", globFullPath))
```suggestion
		return errors.New(fmt.Sprintf("more than one file found for glob '%s': %v", globFullPath, fullPaths))
```

2022-06-27 12:18 UTC, osherdp commented on internal/provider/registry/registry_test.go
> +			fmt.Println(filePath)
is it for debugging?

2022-06-27 12:19 UTC, osherdp commented
@mmartinv can you elaborate on how it was manually tested? thanks in advance

2022-06-30 11:04 UTC, mmartinv commented on internal/provider/ovirt/ignition.go
> +		return errors.New(fmt.Sprintf("more than one file found '%s'", globFullPath))
Done

2022-06-30 11:55 UTC, osherdp commented
@mmartinv ``edge-verify-generated-code`` still failing
can you please do ``skipper make generate``?

2022-06-30 19:39 UTC, osherdp approved these changes

2022-07-01 15:00 UTC, mmartinv commented
/bugzilla refresh

2022-07-06 11:59 UTC, osherdp commented
> @openshift-bot: This pull request references [Bugzilla bug 2100857](https://bugzilla.redhat.com/show_bug.cgi?id=2100857), which is invalid:
> 
> * expected the bug to target the "rhacm-2.6" release, but it targets "---" instead
> 
> Comment `/bugzilla refresh` to re-evaluate validity if changes to the Bugzilla bug are made, or edit the title of this pull request to link to a different bug.

Bug needs to be adjusted to be able to be linked to the PR. See other PRs for examples
/hold

2022-07-07 08:51 UTC, mmartinv commented
/bugzilla refresh

2022-07-07 10:06 UTC, mmartinv commented
/bugzilla refresh

2022-07-07 10:09 UTC, mmartinv commented
/bugzilla refresh

2022-07-07 15:50 UTC, merged