MGMT-2235: Preload host on refresh cluster status (disable/enable)
openshift/assisted-service pull request #409
Opened 2020-09-21 21:46 UTC by RazRegev

2020-09-22 00:24 UTC, RazRegev commented
/hold

2020-09-29 16:03 UTC, ori-amizur requested changes

2020-09-29 16:03 UTC, ori-amizur commented on internal/cluster/common.go
> +		log.Error(dbReply.Error)
This is a dangerous change.  It will panic in case dbReply.Error == nil

2020-09-29 16:03 UTC, ori-amizur commented on internal/bminventory/inventory.go
> +	if err := db.Preload("Hosts").First(&c, filter, clusterID).Error; err != nil {
Why?

2020-09-29 23:51 UTC, RazRegev commented
the relevant pr: https://github.com/openshift/assisted-service/pull/436

2020-09-29 23:51 UTC, closed without merging