MGMT-10866: Compile assisted-service with CentOS stream 9
openshift/assisted-service pull request #4138
Opened 2022-07-14 14:45 UTC by nmagnezi

This is in preparation for upcoming NMState work done in MGMT-8568

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Assignees

/cc @
/cc @

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] Reviewers have been listed
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

2022-07-14 14:57 UTC, nmagnezi commented
/hold
testing with nmstate

2022-07-17 09:26 UTC, nmagnezi commented
/test edge-e2e-ai-operator-ztp

2022-07-18 10:40 UTC, michaellevy101 commented
Looks good!!! @osherdp please review it

2022-07-18 10:40 UTC, michaellevy101 commented
/cc @osherdp

2022-07-18 10:51 UTC, nmagnezi commented
/unhold

2022-07-18 12:51 UTC, osherdp commented on Dockerfile.assisted-service
> +COPY models/go.mod models/go.sum /assisted-service/models/
?
I mean I think those lines are completely redundant. Aren't they?

2022-07-19 08:57 UTC, nmagnezi commented on Dockerfile.assisted-service
> +COPY models/go.mod models/go.sum /assisted-service/models/
no. note that the files under the `models` dir are there because of https://github.com/openshift/assisted-service/pull/3385

2022-07-19 08:57 UTC, nmagnezi commented
/unhold

2022-07-19 09:46 UTC, osherdp requested changes

2022-07-19 11:01 UTC, nmagnezi commented on Dockerfile.assisted-service
> +COPY models/go.mod models/go.sum /assisted-service/models/
Gotcha. Yes, it makes sense to me that we might not need those files under /models.
@filanov, do you agree?

2022-07-19 12:16 UTC, filanov commented on Dockerfile.assisted-service
> +COPY models/go.mod models/go.sum /assisted-service/models/
You can try to remove and see if the build works. if i remember correctly something didn't work as expected.
does the build work without the go.mod files?

2022-07-19 12:20 UTC, nmagnezi commented on Dockerfile.assisted-service
> +COPY models/go.mod models/go.sum /assisted-service/models/
I'll check

2022-07-19 12:26 UTC, osherdp commented on Dockerfile.assisted-service
> +COPY models/go.mod models/go.sum /assisted-service/models/
hmm, actually I'm not sure it works out of the box
I do see ``go mod download`` failing:
```
go mod download: github.com/openshift/assisted-service/api@v0.0.0 (replaced by ./api): reading api/go.mod: open /assisted-service/api/go.mod: no such file or directory
```

2022-07-19 12:29 UTC, osherdp approved these changes
we can handle this api/models.mod thing later on, I wouldn't want to block on it too much

2022-07-19 16:59 UTC, nmagnezi commented
/retest-required

2022-07-19 17:53 UTC, merged