MGMT-11411: Fix image references for the release branch so that they correctly point to :ocm-2.6 instead of :latest
openshift/assisted-service pull request #4208
Opened 2022-07-31 12:29 UTC by eliorerz

/cc @osherdp

2022-07-31 12:31 UTC, osherdp requested changes

2022-07-31 12:31 UTC, osherdp commented on Makefile
> +BUNDLE_METADATA_OPTS ?= --channels=$(BUNDLE_CHANNELS) --default-channel=ocm-2.6kustomization.yaml
probably pasted by mistake

2022-07-31 12:34 UTC, eliorerz commented on Makefile
> +BUNDLE_METADATA_OPTS ?= --channels=$(BUNDLE_CHANNELS) --default-channel=ocm-2.6kustomization.yaml
Yep, sorry for that

2022-07-31 12:37 UTC, osherdp approved these changes

2022-07-31 13:18 UTC, osherdp approved these changes

2022-07-31 16:30 UTC, eliorerz commented
/retest

2022-08-01 07:45 UTC, eliorerz commented
/bugzilla refresh

2022-08-01 07:55 UTC, eliorerz commented
/bugzilla refresh

2022-08-01 15:37 UTC, eliorerz commented
/bugzilla refresh

2022-08-01 15:39 UTC, eliorerz commented
/bugzilla refresh

2022-08-04 08:21 UTC, osherdp commented
/retest
capi should be fixed, disconnected might also be affected by some other change

2022-08-04 11:22 UTC, osherdp commented
/retest

2022-08-04 15:01 UTC, osherdp commented
/retest

2022-08-04 19:29 UTC, osherdp commented
Now that https://github.com/openshift/assisted-service/pull/4238 has been merged we should get a new result
/retest

2022-08-05 07:39 UTC, osherdp commented
It gets us past operator installation now, so let's merge it
/override ci/prow/e2e-ai-operator-ztp-disconnected

2022-08-05 10:24 UTC, merged