MGMT-8890: Add 4.11 single-arch release image to defaults
openshift/assisted-service pull request #4324
Opened 2022-08-29 07:06 UTC by mkowalski

Contributes-to: MGMT-8890

2022-08-29 07:06 UTC, mkowalski commented
/test ?

2022-08-29 07:07 UTC, mkowalski commented
/test edge-verify-generated-code

2022-08-29 07:44 UTC, mkowalski commented
/test edge-verify-generated-code

2022-08-29 13:43 UTC, mkowalski commented
/cc @osherdp

2022-08-29 14:44 UTC, osherdp requested changes

2022-08-29 14:44 UTC, osherdp commented on data/default_release_images.json
> +      "url": "quay.io/openshift-release-dev/ocp-release:4.11.0-arm64",
```suggestion
      "url": "quay.io/openshift-release-dev/ocp-release:4.11.0-aarch64",
```

2022-08-29 14:57 UTC, mkowalski commented on data/default_release_images.json
> +      "url": "quay.io/openshift-release-dev/ocp-release:4.11.0-arm64",
Fixed, thanks!

2022-08-29 15:20 UTC, osherdp approved these changes

2022-08-29 16:42 UTC, osherdp commented
/override ci/prow/edge-e2e-metal-assisted-day2-single-node
ignore, @eliorerz is fixing it

2022-08-29 20:34 UTC, osherdp commented
/hold
Failure seems somewhat related to the changes of this PR

2022-08-30 13:32 UTC, mkowalski commented
/unhold

Indeed that was the case; we didn't foresee shipping single-arch next to multi-arch so the tests were opinionated towards some logic implemented for "only multi-arch" scenario. As the files used by subsystem are directly coming from this repo and not from the separate test files, the test need to be adjusted. Didn't find an easy way to provide a separate configuration to the test so as long as our tests and prod consume the same file, one has to be opinionated ¯\_(ツ)_/¯

2022-08-30 14:39 UTC, osherdp approved these changes

2022-08-30 14:56 UTC, mkowalski commented
/test edge-e2e-metal-assisted-day2-single-node

Seems to almost always fail, let's just retry

2022-08-30 19:54 UTC, merged