NO-ISSUE: Update subsystem docs to use minikube with podman
openshift/assisted-service pull request #4467
Opened 2022-10-04 13:58 UTC by mkowalski

This change allows to use the same setup for test-infra and subsystem. As the default minikube tries to use as much of Docker as possible, we want to explicitly point it to use Podman.

/cc @paul-maidment

2022-10-06 05:53 UTC, nmagnezi requested changes

2022-10-06 08:22 UTC, nmagnezi commented on docs/dev/running-test.md
> +podman network rm minikube
ack. That works :-)

2022-10-06 08:23 UTC, nmagnezi commented
looks good to me.
Just check why `ci/prow/images` fails, and I'll approve it.

2022-10-06 09:16 UTC, mkowalski commented
/retest

It failed because it failed

2022-10-06 09:45 UTC, mkowalski commented
/override ci/prow/images

Not our fault - https://coreos.slack.com/archives/C014N2VLTQE/p1665049417596289

2022-10-07 13:35 UTC, celebdor commented
This made running the subsystem tests much more convenient

2022-10-07 13:35 UTC, celebdor commented
/lgtm

2022-10-07 15:40 UTC, merged