MGMT-10376: Adding a feature usage flag for setting UserManagedNetworking flag in a non-SNO configuration
openshift/assisted-service pull request #4579
Opened 2022-11-06 13:16 UTC by danmanor

Adding a feature usage flag for setting UserManagedNetworking flag in a non-SNO configuration

## List all the issues related to this PR

- [ ] New Feature 
- [x] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [x] Cloud
- [ ] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [x] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

2022-11-06 13:17 UTC, danmanor commented
/hold

2022-11-06 13:21 UTC, danmanor commented
/cc @slaviered

2022-11-06 14:02 UTC, danmanor commented
/cc @osherdp

2022-11-06 14:10 UTC, osherdp commented
adding an e2e test for it:
/test edge-e2e-metal-assisted-none

2022-11-06 14:22 UTC, osherdp requested changes

2022-11-06 14:22 UTC, osherdp commented on internal/usage/consts.go
> +	//Usage of User Managed Networking With Multi Node
nit:
```suggestion
	// Usage of User Managed Networking With Multi Node
```

2022-11-06 14:22 UTC, osherdp commented on internal/bminventory/inventory.go
> +	b.setUsage(swag.BoolValue(params.ClusterUpdateParams.UserManagedNetworking) &&
what happens if the user doesn't provide any argument (which should be reflected with ``nil`` in ``params.ClusterUpdateParams.UserManagedNetworking`` but did set ``UserManagedNetworking`` previously in the cluster?
Won't it override it with false?

2022-11-06 14:22 UTC, osherdp commented on internal/bminventory/inventory.go
> +	b.setUsage(swag.StringValue(cluster.HighAvailabilityMode) == models.ClusterCreateParamsHighAvailabilityModeFull &&
same as ``setProxyUsage``, let's extract this into a function and reuse it in those two occurrences

2022-11-06 14:22 UTC, osherdp commented on internal/bminventory/inventory.go
> +	b.setUsage(swag.BoolValue(params.ClusterUpdateParams.UserManagedNetworking) &&
I think we're missing unit-tests for a couple of possible cases

2022-11-08 13:40 UTC, osherdp commented
/cc @omertuc 
PTAL

2022-11-08 18:15 UTC, danmanor commented
/test edge-e2e-metal-assisted-none

2022-11-08 18:19 UTC, omertuc commented on internal/bminventory/inventory.go
> +	if userManagedNetworking == nil || highAvailabilityMode == nil {
Under what circumstances is highAvailabilityMode nil?

2022-11-08 18:54 UTC, omertuc commented on internal/bminventory/inventory.go
> +	if userManagedNetworking == nil || highAvailabilityMode == nil {
Yes, let's change those tests, to avoid unnecessary code paths in actual non-test code

2022-11-09 15:30 UTC, danmanor commented
/test edge-e2e-metal-assisted-capi

2022-11-09 15:51 UTC, omertuc commented on internal/bminventory/inventory.go
> +func (b *bareMetalInventory) setUserManagedNetworkingAndMultiNodeUsage(userManagedNetworking *bool, highAvailabilityMode *string, usages map[string]models.Usage) {
`highAvailabilityMode` should not be a pointer

2022-11-09 15:53 UTC, omertuc commented on internal/bminventory/inventory.go
> +	b.setUserManagedNetworkingAndMultiNodeUsage(params.ClusterUpdateParams.UserManagedNetworking, cluster.HighAvailabilityMode, usages)
Similarly to the hyperthreading condition a few lines above this one, we should do the != nil check here and pass a non-pointer value to the `setUserManagedNetworkingAndMultiNodeUsage` function

2022-11-14 11:29 UTC, omertuc commented
/test edge-e2e-metal-assisted-capi

2022-11-14 11:54 UTC, danmanor commented
/unhold

2022-11-27 10:12 UTC, osherdp approved these changes

2022-11-27 10:13 UTC, osherdp commented
/test edge-e2e-metal-assisted-none

2022-11-27 10:13 UTC, osherdp commented
/hold
unhold when all checks are complete (including e2e one)

2022-11-27 13:40 UTC, danmanor commented
/test edge-subsystem-aws

2022-11-27 13:43 UTC, danmanor commented
/retest

2022-11-27 16:09 UTC, danmanor commented
/test e2e-agent-compact

2022-11-27 16:12 UTC, danmanor commented
/test edge-e2e-ai-operator-ztp-capi

2022-11-30 07:52 UTC, danmanor commented
/test edge-e2e-metal-assisted-none

2022-11-30 09:41 UTC, danmanor commented
/test edge-e2e-metal-assisted-none

2022-11-30 11:40 UTC, osherdp approved these changes

2022-11-30 14:50 UTC, danmanor commented
/test edge-e2e-ai-operator-ztp-capi

2022-12-01 17:30 UTC, danmanor commented
/test edge-e2e-ai-operator-ztp-capi

2022-12-04 07:10 UTC, danmanor commented
/test edge-e2e-ai-operator-ztp-capi

2022-12-04 09:20 UTC, danmanor commented
/test edge-e2e-metal-assisted-none

2022-12-04 12:10 UTC, danmanor commented
/unhold

2022-12-04 14:01 UTC, danmanor commented on internal/bminventory/inventory.go
> +	if params.ClusterUpdateParams.UserManagedNetworking != nil && cluster.HighAvailabilityMode != nil {
cluster.HighAvailabilityMode is nil in `edge-e2e-ai-operator-ztp-capi`

2022-12-04 15:09 UTC, osherdp approved these changes

2022-12-04 16:08 UTC, danmanor commented
/unhold

2022-12-04 18:04 UTC, merged