MGMT-12400: enable pprof when debug mode for memory profiling
openshift/assisted-service pull request #4712
Opened 2022-12-02 15:52 UTC by rccrdpccl

It looks like the intention was to activate pprof http server if debug mode, but the condition was never matching.

Signed-off-by: Riccardo piccoli <rpiccoli@redhat.com>

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

2022-12-02 15:53 UTC, rccrdpccl commented on cmd/main.go
>  		log.SetLevel(logLevel)
@omertuc do you think this line is still relevant or shall we just get rid of it as we would mostly use the instatiated logger?

2022-12-02 15:53 UTC, rccrdpccl commented
/cc @omertuc @osherdp

2022-12-04 08:09 UTC, osherdp requested changes

2022-12-04 08:09 UTC, osherdp commented on cmd/main.go
>  		log.SetLevel(logLevel)
I think it pretty confusing to see two methods for setting log-level for two different objects
So yes, I think we should refactor it a bit

2022-12-05 12:22 UTC, osherdp approved these changes

2022-12-05 17:13 UTC, osherdp commented
/cherry-pick cloud_hotfix_releases

2022-12-05 20:22 UTC, merged