OCPBUGS-4493: do not mutate ACI post installation start
openshift/assisted-service pull request #4723
Opened 2022-12-05 18:12 UTC by slaviered

Upon upgrade from older versions mutating webhook kicks in and try to mutate existing CRs that are in post-install status. Then the mutated ACO goes through the validation webhook that rejects it due to an attempt to change immutable fields post installation.

The result is failure to upgrade and to delete or update those existing CRs.

This PR prevents mutating post-install.

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

2022-12-05 18:13 UTC, slaviered commented
/test all

2022-12-05 18:13 UTC, slaviered commented
/assign @mhrivnak

2022-12-05 18:18 UTC, slaviered commented
cc: @filanov @gamli75

2022-12-05 18:49 UTC, slaviered commented
/test all

2022-12-05 20:18 UTC, slaviered commented
/assign @filanov

2022-12-05 20:46 UTC, mhrivnak requested changes

2022-12-05 20:46 UTC, mhrivnak commented on pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_mutating_hook.go
> +	if !installAlreadyStarted(newObject.Status.Conditions) || !newObject.DeletionTimestamp.IsZero() {
Shouldn't this be `&&`? We need to ensure that installation didn't start **and** deletion is not in-progress.

2022-12-05 20:46 UTC, mhrivnak commented on pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_mutating_hook.go
> +	if !installAlreadyStarted(newObject.Status.Conditions) || !newObject.DeletionTimestamp.IsZero() {
Also, we want `DeletionTimestamp.IsZero()` to be `true`, not `false`.

2022-12-05 21:37 UTC, slaviered commented
@filanov the PR comes with some additional unit tests but in addition it should be tested e2e in an upgrade scenario. The latter is currently done manually

2022-12-05 21:39 UTC, slaviered commented
/uncc: @paul-maidment 
/uncc: @jhernand

2022-12-06 06:38 UTC, filanov commented
/hold 
until manual upgrade test is completed

2022-12-06 15:07 UTC, eranco74 commented on pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_mutating_hook.go
> +	if !installAlreadyStarted(newObject.Status.Conditions) && newObject.DeletionTimestamp.IsZero() {
I think it should be 
```suggestion
	if !installAlreadyStarted(newObject.Status.Conditions) || newObject.DeletionTimestamp.IsZero() {
```
In both cases we won't want to do the UMN patch

2022-12-06 21:14 UTC, chadcrum commented
/lgtm - First duplicated the issue with existing builds, then tried again with a build from this branch and I was able to remove the aci without issue.

2022-12-07 06:49 UTC, filanov approved these changes

2022-12-07 06:50 UTC, filanov commented
/unhold

2022-12-07 11:39 UTC, merged

2022-12-07 11:53 UTC, slaviered commented
/cherry-pick release-ocm-2.6

2022-12-12 09:28 UTC, slaviered commented
/cherry-pick release-ocm-2.7