MGMT-12875: fail gracefully when konnectivity is missing
openshift/assisted-service pull request #4830
Opened 2022-12-25 13:42 UTC by slaviered

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

2022-12-25 13:42 UTC, slaviered commented
/assign @danielerez

2022-12-25 16:09 UTC, danielerez commented on internal/controller/controllers/hypershiftagentserviceconfig_controller.go
> +		err := pkgerror.Wrap(err, fmt.Sprintf("Failed to retrieve konnectivity-agend Deployment from namespace %s", asc.namespace))
* need another var for err ("err" shadows declaration)
* s/agend/agent

2022-12-25 16:09 UTC, danielerez commented on internal/controller/controllers/hypershiftagentserviceconfig_controller_test.go
> +			fmt.Sprintf("Failed to retrieve konnectivity-agend Deployment from namespace %s",
s/agend/agent

2022-12-25 16:25 UTC, romfreiman commented
Connectivity?

2022-12-25 16:29 UTC, osherdp requested changes
just some typos

2022-12-25 16:29 UTC, osherdp commented on internal/controller/controllers/hypershiftagentserviceconfig_controller.go
> +		err := pkgerror.Wrap(e, fmt.Sprintf("Failed to retrieve konnectivity-agend Deployment from namespace %s", asc.namespace))
```suggestion
		err := pkgerror.Wrap(e, fmt.Sprintf("Failed to retrieve konnectivity-agent Deployment from namespace %s", asc.namespace))
```

2022-12-25 16:29 UTC, osherdp commented on internal/controller/controllers/hypershiftagentserviceconfig_controller_test.go
> +			fmt.Sprintf("Failed to retrieve konnectivity-agend Deployment from namespace %s",
```suggestion
			fmt.Sprintf("Failed to retrieve konnectivity-agent Deployment from namespace %s",
```

2022-12-25 16:38 UTC, danielerez commented
> Connectivity?

It's actually just the naming for the k8s service :)
https://kubernetes.io/docs/tasks/extend-kubernetes/setup-konnectivity/

2022-12-26 09:03 UTC, danielerez commented
/test edge-e2e-ai-operator-ztp-hypershift-zero-nodes

2022-12-26 19:16 UTC, slaviered commented
/retest-required

2022-12-28 10:28 UTC, slaviered commented
/retest-required

2022-12-28 12:51 UTC, slaviered commented
/retest-required

2022-12-28 13:26 UTC, danielerez commented
/lgtm

2022-12-28 14:27 UTC, slaviered commented
/override ci/prow/edge-e2e-ai-operator-ztp-hypershift-zero-nodes
/override  ci/prow/edge-e2e-ai-operator-ztp-capi

2023-01-01 06:55 UTC, slaviered commented
/retest-required

2023-01-01 09:12 UTC, slaviered commented
/override ci/prow/edge-e2e-metal-assisted

2023-01-01 09:19 UTC, merged