MGMT-13398 omit BMH secret from day2 spoke worker
openshift/assisted-service pull request #5009
Opened 2023-02-28 10:18 UTC by slaviered

BMH secret is copied to the spoke only in adding the day2 worker to spoke cluster scenario.

The presence of the secret on the spoke creates a discrepancy between the status of the BMH of the day2 worker and the those of the masters and day1 workers on the spoke cluster.

By not copying the BMH secret, we align the status of all cases to unmanaged.

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

2023-02-28 10:19 UTC, slaviered commented
/assign @eranco74 
/assign @carbonin

2023-02-28 10:34 UTC, slaviered commented
/test all

2023-03-01 17:18 UTC, slaviered commented
/test edge-e2e-ai-operator-ztp

2023-03-01 21:21 UTC, carbonin requested changes
As a follow-up to this I'm curious if you also remove the spoke BMH handling if anything would change.

In my tests the BMHs for the spoke workers didn't look like we created them.

2023-03-02 07:45 UTC, slaviered commented on internal/controller/controllers/bmh_agent_controller.go
> +		bmhSpoke.Spec.BMC = bmh_v1alpha1.BMCDetails{}
Yes we do. If the credential field is filled, the BMO looks for the secret and when not finding it - fails the reconciliation.

2023-03-02 11:20 UTC, slaviered commented on internal/controller/controllers/bmh_agent_controller.go
> +// func (r *BMACReconciler) newSpokeBMHSecret(secret *corev1.Secret) (*corev1.Secret, controllerutil.MutateFn) {
removed

2023-03-02 13:46 UTC, carbonin commented on internal/controller/controllers/bmh_agent_controller.go
> -		bmhSpoke.Spec.ExternallyProvisioned = true
It might be worth explaining why this is being removed in the commit message.

2023-03-02 13:59 UTC, carbonin commented
>As a follow-up to this I'm curious if you also remove the spoke BMH handling if anything would change.
> In my tests the BMHs for the spoke workers didn't look like we created them.

I misremembered, it was a difference between the expected and actual machines and it was day-1, so I don't think it matters for this work.

2023-03-05 07:49 UTC, slaviered commented
/test edge-e2e-metal-assisted

2023-03-05 11:17 UTC, filanov approved these changes

2023-03-05 11:22 UTC, merged