MGMT-14633: WIP include manifest information in the log download
openshift/assisted-service pull request #5777
Opened 2023-12-05 09:58 UTC by paul-maidment

When downloading the logs it is desired that the manifests of the cluster are also included in the download so that these may be examined.

This PR introduces that functionality.

## List all the issues related to this PR

- [x] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [x] Manual (Elaborate on how it was tested)
  Manually set up a cluster with manifests and then triggered a download of the manifests, a CURL request similar to 
  `curl -X GET $SERVICE_URI/api/assisted-install/v2/clusters/61e94f28-bbd7-4719-b555-d7d7f9d5cc60/logs?logs_type=all --output logs.tar.gz` was used. 
  I also checked in the UI to ensure that the download looks appropriate.
- [] No tests needed

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

2023-12-05 14:30 UTC, paul-maidment commented on internal/cluster/cluster.go
> +		if exists {
Good suggestion..taken!

2023-12-07 14:13 UTC, carbonin requested changes

2023-12-07 14:13 UTC, carbonin commented on internal/cluster/cluster.go
> +		if exists {
I think you want `!exists`, right?

2023-12-11 19:41 UTC, carbonin commented on internal/cluster/cluster.go
> +		_ = m.uploadDataAsFile(ctx, log, string(fileContent), fileName, objectHandler)
We should probably at least log here if this errors, right?

2023-12-14 09:44 UTC, paul-maidment commented
/retest

2023-12-14 09:46 UTC, paul-maidment commented
/retest

2023-12-14 12:11 UTC, paul-maidment commented
/retest

2023-12-14 16:40 UTC, paul-maidment commented
/retest

2023-12-14 20:11 UTC, carbonin approved these changes

2023-12-14 23:03 UTC, merged