MGMT-16373: KubeAPI - Ensure that ISO type is full-iso when cpuarchitecture is S390x
openshift/assisted-service pull request #5825
Opened 2023-12-18 10:36 UTC by paul-maidment

Presently when an infraenv is created via KubeAPI for the S390x architecture it is created with the default "minimum-iso" imagetype. This is incompatible with S390x.

This PR makes sure that the imagetype is updated to "full-iso" to maintain compatibility.

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [x] Automation (CI, tools, etc)
- [x] Cloud
- [x] Operator Managed Deployments
- [] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [x] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

2023-12-18 11:47 UTC, filanov commented
/assign @carbonin

2023-12-18 13:58 UTC, carbonin requested changes
This looks like it's missing handling the create case [here](https://github.com/openshift/assisted-service/blob/e56197390fd182c3e43682dd3c9d5c74e7b206bc/internal/controller/controllers/infraenv_controller.go#L479)

Can we maybe test this in subsystem kube API tests?

2023-12-19 09:18 UTC, paul-maidment commented
> This looks like it's missing handling the create case [here](https://github.com/openshift/assisted-service/blob/e56197390fd182c3e43682dd3c9d5c74e7b206bc/internal/controller/controllers/infraenv_controller.go#L479)
> 
> Can we maybe test this in subsystem kube API tests?

This is the only location from which a call to the create method is made

https://github.com/openshift/assisted-service/blob/e56197390fd182c3e43682dd3c9d5c74e7b206bc/internal/controller/controllers/infraenv_controller.go#L384

Immediately, and unconditionally, a call is made to `updateInfraEnv` where the change of ISO type is applied.

As far as I can see this leaves no uncovered edge cases.

I can certainly add a subsystem test though...

2023-12-19 14:03 UTC, carbonin commented
>As far as I can see this leaves no uncovered edge cases.
>I initially considered making the same change inside the createInfraEnv method but it would make no semantic difference. As this method is private also, I feel it's best to leave it as is.

I disagree. I think it's best not to rely on this pattern. We're setting the image type in create to something incorrect and we shouldn't do that. I could very easily imagine someone making those calls to create and update mutually exclusive in a refactoring and I think they would be correct to do so. 

It should be easy enough to put the image type logic into a helper function and use it in both places.

Either way we should have a test to ensure the image is set correctly for both create and update cases.

2023-12-20 17:57 UTC, paul-maidment commented
> > As far as I can see this leaves no uncovered edge cases.
> > I initially considered making the same change inside the createInfraEnv method but it would make no semantic difference. As this method is private also, I feel it's best to leave it as is.
> 
> I disagree. I think it's best not to rely on this pattern. We're setting the image type in create to something incorrect and we shouldn't do that. I could very easily imagine someone making those calls to create and update mutually exclusive in a refactoring and I think they would be correct to do so.
> 
> It should be easy enough to put the image type logic into a helper function and use it in both places.
> 
> Either way we should have a test to ensure the image is set correctly for both create and update cases.

Agreed.

I have made sure we apply the change to image type on create as well as update and added a subsystem test to check this.

2023-12-20 20:28 UTC, carbonin approved these changes

2023-12-20 20:32 UTC, merged