[MGMT-2317] Added boot discovery iso over ipxe from grub docs
openshift/assisted-service pull request #612
Opened 2020-10-26 12:41 UTC by mvazquezc

Adds documentation around how to boot a discovery iso from an iPXE server using GRUB.

2020-11-02 16:43 UTC, avishayt commented on docs/user-guide/boot-discovery-iso-over-ipxe-from-grub.md
> +    podman run -e BASE_URL=http://devscripts2ipv6.e2e.bos.redhat.com:8080/ipxe/ -e ISO_URL=http://10.19.115.219:6008/api/assisted-install/v1/clusters/1c907764-6354-409e-9a2e-93582497545a/downloads/im
```suggestion
    podman run -e BASE_URL=http://devscripts2ipv6.e2e.bos.redhat.com:8080/ipxe/ -e ISO_URL=<REPLACE WITH ISO UR> -v /tmp/ipxe/ai:/data:Z --net=host -it --rm quay.io/ohadlevy/ai-ipxe:latest
```

2020-11-02 16:43 UTC, avishayt commented on docs/user-guide/boot-discovery-iso-over-ipxe-from-grub.md
> +    podman run  -v ${IPXE_DIR}:/app:ro,Z -p 8080:8080 -d --rm bitnami/nginx:latest
```suggestion
    podman run -v ${IPXE_DIR}:/app:ro,Z -p 8080:8080 -d --rm bitnami/nginx:latest
```

2020-11-02 16:46 UTC, avishayt commented on docs/user-guide/boot-discovery-iso-over-ipxe-from-grub.md
> +    ~~~
Where does this go?

2020-11-02 16:46 UTC, avishayt commented on docs/user-guide/boot-discovery-iso-over-ipxe-from-grub.md
> +3. Create a iPXE script for running the DHCP request and for chainload the pxe files from the server configured previously
```suggestion
3. Create an iPXE script for running the DHCP request and for chainload the PXE files from the server configured previously
```

2020-11-04 08:44 UTC, mvazquezc commented on docs/user-guide/boot-discovery-iso-over-ipxe-from-grub.md
> +    ~~~
It is the output from the curl command.

2021-01-13 17:13 UTC, droslean commented
For the record: I tried to follow those steps but without any success. I am not sure if there are any other dependencies but it worth checking and include those in this document.

2021-01-14 12:47 UTC, droslean commented
It seems that booting from iPXE really depends on the hardware. I will continue to investigate.

2021-04-28 09:17 UTC, flaper87 commented
Is this PR still needed ? O can we close it? :)

2021-05-11 07:41 UTC, flaper87 requested changes
@mvazquezc thanks for writing these docs. 

I was browsing the docs we have and noticed that there is already some documentation for iPXE deployment. You can find it here: https://github.com/openshift/assisted-service/blob/master/docs/user-guide/deploy-on-bare-metal.md#ipxe

* Were you aware of it? 
* How does the existing one differs from the one you wrote?
* Would it be possible to merge them? Maybe link this one in the `Manual` section of the existing one?

2021-05-14 07:25 UTC, mvazquezc commented
> @mvazquezc thanks for writing these docs.
> 
> I was browsing the docs we have and noticed that there is already some documentation for iPXE deployment. You can find it here: https://github.com/openshift/assisted-service/blob/master/docs/user-guide/deploy-on-bare-metal.md#ipxe
> 
> * Were you aware of it?

When this PR was created I believe that doc didn't exist.

> * How does the existing one differs from the one you wrote?

It uses GRUB to boot into iPXE, it's useful for environments where you don't have access to the BMC, like cloud providers.

> * Would it be possible to merge them? Maybe link this one in the `Manual` section of the existing one?

Works for me.

2021-07-02 09:12 UTC, flaper87 commented
/close

Closing for inactivity. Reopen when ready to update/merge

2021-07-02 09:12 UTC, closed without merging