add ocp4.15 osImages on ACM 2.9
openshift/assisted-service pull request #6189
Opened 2024-04-15 07:18 UTC by mihirlele

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [✔ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [✔ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [✔ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Checklist

- [✔ ] Title and description added to both, commit and PR.
- [✔ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [✔ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

2024-04-15 12:09 UTC, danmanor commented
/ok-te-test

2024-04-15 12:21 UTC, danmanor commented
/ok-to-test

2024-04-15 12:47 UTC, danmanor requested changes

2024-04-15 12:47 UTC, danmanor commented on deploy/podman/configmap.yml
> +  OS_IMAGES: '[{"openshift_version":"4.9","cpu_architecture":"x86_64","url":"https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.9/4.9.45/rhcos-4.9.45-x86_64-live.x86_64.iso","v
Redundant in podman deployment

2024-04-15 12:47 UTC, danmanor commented on openshift/template.yaml
> +  value: '[{"openshift_version":"4.9","cpu_architecture":"x86_64","url":"https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.9/4.9.45/rhcos-4.9.45-x86_64-live.x86_64.iso","versi
Redundant changes in this file. it is for SaaS deployment

2024-04-15 12:47 UTC, danmanor commented
/cc @carbonin

2024-04-16 01:06 UTC, mihirlele reviewed
Made the changes as per the comments

2024-04-16 03:14 UTC, mihirlele commented
@danmanor I have rolled back the changes in the files that you said were not required. Please check and let me know if anything else is required to be done.

2024-04-16 07:40 UTC, danmanor commented
/lgtm

2024-04-16 07:41 UTC, danmanor commented
@mihirlele please run `skipper make generate` to pass the code generation test

2024-04-17 14:49 UTC, mihirlele commented
/abort

2024-04-23 05:59 UTC, mihirlele commented
obsolete due to https://github.com/openshift/assisted-service/pull/6201. Closing

2024-04-23 05:59 UTC, closed without merging