updated mce_operator to allow hosts with 100MB less memory than required
openshift/assisted-service pull request #6660
Opened 2024-08-07 12:51 UTC by giladravid16

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

2024-08-07 14:25 UTC, omertuc requested changes

2024-08-07 14:25 UTC, omertuc commented on internal/operators/mce/config.go
> +	MaximumMemoryRequirementOffset int64 = 100
```suggestion
	// How much we allow the user to deviate from our official
	// minimum. Some setups (e.g. VMs) might give just a bit less
	// than requested, so we shouldn't be too strict about it
	MemoryRequirementToleranceMiB int64 = 100
```

2024-08-08 09:04 UTC, rccrdpccl commented
[MGMT-16212](https://issues.redhat.com//browse/MGMT-16212) talks about generic requirements, but the change seems specific to the MCE operator. @giladravid16 could you please clarify what are the intentions of this PR by updating description and title accordingly?

2024-08-08 10:10 UTC, giladravid16 commented
[MGMT-16212](https://issues.redhat.com//browse/MGMT-16212) is specifically for the assisted-installer component and the MCE operator handles the logic of validating the hosts before installation

2024-08-08 10:46 UTC, rccrdpccl commented
> [MGMT-16212](https://issues.redhat.com//browse/MGMT-16212) is specifically for the assisted-installer component and the MCE operator handles the logic of validating the hosts before installation

What do you mean by "specifically for the assisted-installer component"? Is this PR intention to be flexible with requirements under all circumstances, or only when deploying MCE?
Please do change the description to of this PR to describe what are we trying to do exactly here

The MCE operator should handle logic of additional requirements due to the MCE operator deployment. For generic/total requirements I think [this](https://github.com/openshift/assisted-service/blob/885904784c71d90ab4014c096e3348d08b174849/internal/hardware/validator.go#L297) is the place that handles them

2024-08-08 10:48 UTC, omertuc commented
I missed that the code change was in the MCE requirements, that was not the intention. The ticket wants us to address the final memory requirement, not just for the MCE operator

2024-08-08 13:04 UTC, eliorerz commented
@giladravid16 Nice work, few things:
- Please fix the commit messages.
Make sure the commit message start with `MGMT-16212: <Your commit message here>`.  Also remove the 'merge' commit, looks like it's not needed.
- Add description to this PR explaining the changes done here and the decision made (if needed)

2024-08-08 14:24 UTC, giladravid16 commented
I'll write here what I understood the flow is and what should be done.

There are 4 function that are used to calculate whether the host has enough memory and they are divided into 2 groups:
1. are used to check if the host has enough memory for it's role (role memory requirement + operators' host memory requirement)
2. are used to check if the host has enough memory in general by comparing it's memory to the minimum of worker and master (or SNO if it is SNO).

But all 4 functions use the [versioned host requirements](https://github.com/openshift/assisted-service/blob/master/internal/hardware/validator.go#L511) so it is best to change what is returned from that to already take the tolerance into account. So the function that should be updated is [this.](https://github.com/openshift/assisted-service/blob/master/internal/hardware/versioned-requirements.go#L96)

Is this correct?

2024-08-11 12:04 UTC, giladravid16 commented
/retest-required

2024-08-13 06:28 UTC, eliorerz commented
/ok-to-test

2024-08-14 16:07 UTC, giladravid16 commented
/retest

2024-08-15 05:29 UTC, giladravid16 commented
/retest

2024-08-16 05:52 UTC, giladravid16 commented
/retest

2024-08-16 15:00 UTC, omertuc commented
Please make sure to include your summary inside the commit message as well, so that the motivation is accessible through `git blame`

![image](https://github.com/user-attachments/assets/9327f342-48b1-46d4-a953-4c1c67226eec)

2024-08-18 08:31 UTC, eliorerz approved these changes
LGTM

2024-08-18 09:54 UTC, merged