OCPBUGS-32592: Add detached annotation to prevent unbinding Agent
openshift/assisted-service pull request #6748
Opened 2024-09-13 17:14 UTC by CrystalChun

In the hypershift case, when we're simulating deleting clusters from a user's perspective, it removes the ClusterDeployment the Agents are bound to, and that causes the Agents to begin unbinding. This adds an annotation that, when present, prevents the Agent from going through unbinding in both BMH scenario and BIY scenario.

## List all the issues related to this PR

- [x] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [x] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [x] Manual (Elaborate on how it was tested) - will do manual test and update here 
- [ ] No tests needed

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

/cc @carbonin

2024-09-13 17:22 UTC, CrystalChun commented
/test ?

2024-09-13 17:24 UTC, CrystalChun commented
/test edge-e2e-ai-operator-ztp

2024-09-16 18:29 UTC, carbonin requested changes
I'm not really sure what effect this would have.

The cluster reference in the agent CR would be removed in any case right? So now we don't have a cluster reference in the CR spec, but haven't unbound the agent.

Also a detached annotation that just acts on unbind scenarios is a bit strange.

I'd prefer to investigate other ways for dealing with this situation for now.

2024-09-20 14:44 UTC, CrystalChun commented
/close
Taking a different approach in new PR https://github.com/openshift/hypershift/pull/4741

2024-09-20 14:44 UTC, closed without merging