MGMT-18618: Fix local rhsso deployment
openshift/assisted-service pull request #6779
Opened 2024-09-18 17:52 UTC by dudyas6

This PR fixes the local deployment of assisted-service with `AUTH_TYPE=rhsso`, previously was failing on creating authenticator, due to invalid `JWKS_URL`.
Also adds an option to insert custom `JWKS_URL` via environment variable.

JWKS_URL from configmap after deploying :
`JWKS_URL: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/certs`

ensure all pods are running :
![image](https://github.com/user-attachments/assets/1acb2806-04c6-4808-9514-c726c4f75a8d)

logs from assisted service pods :
`time="2024-09-18T17:35:16Z" level=info msg="Created rhsso authenticator" func=github.com/openshift/assisted-service/pkg/auth.NewAuthenticator file="/assisted-service/pkg/auth/authenticator.go:60" pkg=auth`
`time="2024-09-18T17:35:51Z" level=info msg="Starting http handler on :8090..."`

`curl -X GET "http://10.6.48.63:8090/api/assisted-install/v2/clusters" -H "Authorization: Bearer "
{"code":401,"message":"Authorization header format must be Bearer {token}"}
`
## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [X] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [x] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Checklist

- [X] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [X] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

2024-09-18 18:20 UTC, jhernand commented
/lgtm

2024-09-19 07:30 UTC, jhernand commented
/approve

2024-09-19 09:29 UTC, eifrach requested changes

2024-09-19 09:29 UTC, eifrach commented on tools/deploy_assisted_installer_configmap.py
> +JWKS_URL = os.environ.get("JWKS_URL", "https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/certs")
let’s keep the command line, better to have  backward compatibility 


```suggestion
parser.add_argument("--jwks-url", default=os.environ.get('JWKS_URL', "https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/certs")
```

2024-09-19 12:27 UTC, dudyas6 commented
@danmanor

2024-09-19 12:29 UTC, danmanor approved these changes

2024-09-19 12:37 UTC, merged