MGMT-1262 Allow the overriding of the rhcos image
openshift/assisted-service pull request #693
Opened 2020-11-18 02:02 UTC by asalkeld

2020-11-18 06:36 UTC, avishayt requested changes
Looks like this is MGMT-2262, not 1262.  Can you please explain why you need to override the image?

2020-11-19 02:03 UTC, asalkeld commented
> Looks like this is MGMT-2262, not 1262. Can you please explain why you need to override the image?

Sorry @avishayt typo.. it's 1263 - i'll fix the headline

2020-11-19 06:57 UTC, avishayt approved these changes

2020-11-19 13:44 UTC, eranco74 reviewed
Looks good, just a typo

2020-11-19 13:44 UTC, eranco74 commented on internal/common/error_utils.go
> +		Code:   swag.String(fmt.Sprint(http.StatusInternalServerError)),
```suggestion
		Code:   swag.String(fmt.Sprintf(http.StatusInternalServerError)),
```

2020-11-19 13:46 UTC, eranco74 commented
@asalkeld 
Your commit message is missing either a JIRA issue ('JIRA-1111'), a GitHub issue ('#39').

[2020-11-19T02:03:57.255Z] You can also ignore the ticket checking with 'NO-ISSUE'.

2020-12-03 11:09 UTC, avishayt approved these changes

2020-12-20 13:48 UTC, YuviGold commented
/retest

2020-12-20 14:20 UTC, merged