MGMT-3295: On installation delete previews cluster logs
openshift/assisted-service pull request #811
Opened 2020-12-20 01:17 UTC by RazRegev

We saw in some triaging tickets that when we retrieve failed cluster
logs we can get hosts that were part of the previews installation.
In addition, if a host was re-registered with the same dns, we will
get duplicated log files after the second installation.
To avoid this we can simply delete previews installation log files
just before starting the new installation.

2020-12-20 07:01 UTC, filanov approved these changes

2020-12-20 07:01 UTC, filanov requested changes
what about tests?

2020-12-20 08:48 UTC, tsorya commented on internal/bminventory/inventory.go
> +	if err := b.clusterApi.DeleteClusterLogs(ctx, &cluster, b.objectHandler); err != nil {
Can u please add delete logs_collected_at flag too? Lets clearer all the logs relevant stuff before starting installation

2020-12-21 06:49 UTC, avishayt commented
s/previews/previous/

2020-12-21 06:55 UTC, filanov commented on internal/cluster/cluster_test.go
> +	It("logs flags are cleared test", func() {
no bad flows?

2020-12-21 08:51 UTC, tsorya commented on internal/cluster/cluster.go
> +	if err := m.DeleteClusterLogsFromS3(ctx, c, objectHandler); err != nil {
lets change the order, first delete flags and only then files

2020-12-21 10:19 UTC, tsorya commented on internal/cluster/cluster.go
> +		if h.LogsCollectedAt == resetVal {
no need too

2020-12-21 10:19 UTC, tsorya commented on internal/cluster/cluster.go
> +	if c.ControllerLogsCollectedAt != resetVal {
same

2020-12-21 10:42 UTC, RazRegev commented
/hold

2020-12-21 12:02 UTC, filanov commented on internal/cluster/cluster.go
> +func (m *Manager) DeleteClusterLogsFromS3(ctx context.Context, c *common.Cluster, objectHandler s3wrapper.API) error {
```suggestion
func (m *Manager) DeleteClusterLogs(ctx context.Context, c *common.Cluster, objectHandler s3wrapper.API) error {
```

2020-12-22 22:04 UTC, RazRegev commented
opened https://github.com/openshift/assisted-service/pull/821

2020-12-22 22:04 UTC, closed without merging